### PR TITLE
optimized website for mobile view.

### PR DESCRIPTION
**Pull request by ShreyasSahoo**

### CODE REVIEW

**Comment by ShreyasSahoo** [comment]
Please add hacktoberfest-accepted label to it.

**Comment by YoshithaRathnayake** [comment]
> Please add hacktoberfest-accepted label to it.

Can you send me a screenshot of these changes in the mobile view? @ShreyasSahoo

**Comment by ShreyasSahoo** [comment]
Screenshot 2022-10-21 at 8 41 17 AM

**Comment by ShreyasSahoo** [comment]
Screenshot 2022-10-21 at 8 46 19 AM
This was the original view of the website in a IPhone SE.

**Comment by YoshithaRathnayake** [comment]
> Screenshot 2022-10-21 at 8 41 17 AM

Nice @ShreyasSahoo !

**Pull request merged**
