### PR TITLE
Completely Modified the README.md file into a new one 

### PR DESCRIPTION
**Pull request by Arcturus22**
I have entirely modified and added new designs to the Markdown file(README.md). I have added text and information about the website and the application. I have taken references from the README.md file you shared. I have added the details accordingly.

### CODE REVIEW

**Comment by Arcturus22** [comment]
@YoshithaRathnayake 
This Pull Request is regarding Issue #42

**Comment by Arcturus22** [comment]
This is how it looks right now-
Img-1

Img-2

Img-3

**Review by YoshithaRathnayake — APPROVED** [review]
Wow, Awesome!, I didn't expect a change like this from you. Thank You very much @Arcturus22

**Comment by Arcturus22** [comment]
> Wow, Awesome!, I didn't expect a change like this from you. Thank You very much @Arcturus22

Most Welcome!

**Pull request merged**
