### PR TITLE
Removed the bold from font style property in .title class of css file

### PR DESCRIPTION
**Pull request by Abhishekgupta204**
The bold from font style property in .title class of css file has been removed.

### CODE REVIEW

**Comment by Abhishekgupta204** [comment]
Issue no. #81 resolved.
Please accept my pull request.

**Review by YoshithaRathnayake — APPROVED** [review]
Good Job !
Thank You @Abhishekgupta204

**Comment by YoshithaRathnayake** [comment]
https://github.com/all-contributors please add @Abhishekgupta204 for infrastructure, tests and code

**Comment by YoshithaRathnayake** [comment]
@all-contributors please add @Abhishekgupta204 for infrastructure, tests and code

**Pull request merged**
