### PR TITLE
Remove the background color of the paragraph

### PR DESCRIPTION
**Pull request by MartinMaphutseng**
Remove background colour from paragraph. Changed text colour for visibility.

### CODE REVIEW

**Comment by YoshithaRathnayake** [comment]
Can you send me a screenshot of this change @MartinMaphutseng

**Review by YoshithaRathnayake — APPROVED** [review]
Good Job !
Thank You @MartinMaphutseng

**Comment by MartinMaphutseng** [comment]
Screenshot (282)

Picture of result

**Comment by YoshithaRathnayake** [comment]
> Screenshot (282)
> 
> Picture of result

Thanks @MartinMaphutseng

**Pull request merged**
