### PR TITLE
Add yaml in used programming languages

### LINKED ISSUE #168: Add Yaml for the readme.md file
Add Yaml for the readme.md file

image

### PR DESCRIPTION
**Pull request by Roxie2003**
## Purpose

The purpose of this Pull Request is to fix #168 

## Goals

Adding YAML in used programming languages section

### Screenshots
  
image

### Preview Link

https://github.com/Roxie2003/CALCULATOR-WEBSITE/blob/30a1b39d7934e45d996f6daf99d5ab0cbd06d940/README.md

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by YoshithaRathnayake — APPROVED** [review]
Good Job !
Thank You @Roxie2003

**Comment by Roxie2003** [comment]
Can u pls add hacktobertfest-accepted label...

**Comment by YoshithaRathnayake** [comment]
> Can u pls add hacktobertfest-accepted label...

Oh sorry I couldn't but it doesn't matter bcs an approved the changes @Roxie2003 

image

**Comment by Roxie2003** [comment]
Thanks 👍... it's added now

**Comment by YoshithaRathnayake** [comment]
> Thanks 👍... it's added now

Any time

**Pull request merged**
