### PR TITLE
Added some styling to the nav bar

### PR DESCRIPTION
**Pull request by aksy2512**
## Purpose
The purpose of this Pull Request is to fix #187 

## Approach

I added linear gradient and a good hover effect in CSS.

### Screenshots

image

  
### Preview Link

https://pr-188-CALCULATOR-WEBSITE.surge.sh/

### CODE REVIEW

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
Can you change the nav label font color to a darker color @aksy2512

**Comment by aksy2512** [comment]
@YoshithaRathnayake I have done some changes please have a look 
image

**Comment by YoshithaRathnayake** [comment]
So sorry for the late request bcs I have examinations in our school in these days. @aksy2512

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
Can you reduce the height of the navbar bcs its ugly if it is very tall @aksy2512

**Review by YoshithaRathnayake — APPROVED** [review]
Good Job !
Thank You @aksy2512

**Pull request merged**
