### PR TITLE
Changed the title of the page to CALCULATOR

### PR DESCRIPTION
**Pull request by Abhishekgupta204**
Removed the "| YOSHITHA" part from the heading and changed the title to CALCULATOR.

### CODE REVIEW

**Comment by Abhishekgupta204** [comment]
Issue no. #68 resolved.
Please accept my pull request.

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
No commits have been commited, can you add the changes again @Abhishekgupta204

**Comment by YoshithaRathnayake** [comment]
image

Still its there, here file changed 0

**Review by YoshithaRathnayake — APPROVED** [review]
Good Job !
Thank You @Abhishekgupta204

**Pull request merged**
