### PR TITLE
Added a functioning Download SVG icon inside the Download button .

### PR DESCRIPTION
**Pull request by octosapien**
A functioning Download SVG icon has been added inside the Download button alongside the "Download" text . 
The icon has been added as a Scalable Vector Graphic icon .

### CODE REVIEW

**Comment by octosapien** [comment]
This resolves issue #15 .
Please , accept my Pull Request .

**Comment by octosapien** [comment]
I am attaching Screenshots of teh resulting changes of this Pull Request .
.
Screenshot_hackto_71
.
Screenshot_hackto_7

**Comment by YoshithaRathnayake** [comment]
No, this is not an issue assigned to you, do the issues assigned to you only

**Comment by octosapien** [comment]
Alright , sure .

**Pull request closed without merging**
