### PR TITLE
Fixed the Download Icon inside the download button

### PR DESCRIPTION
**Pull request by Abhishekgupta204**
Fixed the Download Icon inside the download button

### CODE REVIEW

**Comment by Abhishekgupta204** [comment]
Issue no. #15 resolved.
Please accept my pull request.

**Comment by YoshithaRathnayake** [comment]
> Issue no. #15 resolved. Please accept my pull request.

Please send me a screenshot of this change @Abhishekgupta204

**Comment by Abhishekgupta204** [comment]
image
This is how it looks.

**Review by YoshithaRathnayake — APPROVED** [review]
Good Job !
Thank You @Abhishekgupta204

**Pull request merged**
