### PR TITLE
Added some styling to the nav bar

### LINKED ISSUE #182: Customize the nav bar to a beautiful design
Customize the nav bar to a beautiful design

### PR DESCRIPTION
**Pull request by aksy2512**
The purpose of this Pull Request is to fix #182 

I have added some styling to beautify the navigation bar.

image

Preview link:-
https://pr-187-calculator-website.surge.sh/

### CODE REVIEW

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
Add the preview link to the pr template, why did you remove it? @aksy2512

**Comment by aksy2512** [comment]
Hey! Can you please tell me what is the preview link? I didn't remove anything from the code

**Comment by YoshithaRathnayake** [comment]
> Hey! Can you please tell me what is the preview link? I didn't remove anything from the code

You remove the comments in the PR Template no? @aksy2512

**Comment by aksy2512** [comment]
Ohh! I am very sorry. Should I create a new PR for the same?

**Comment by YoshithaRathnayake** [comment]
> Ohh! I am very sorry. Should I create a new PR for the same?

https://pr-187-calculator-website.surge.sh/ this is your preview link @aksy2512 add it to the pr template comment

**Comment by aksy2512** [comment]
> > Ohh! I am very sorry. Should I create a new PR for the same?
> 
> https://pr-187-calculator-website.surge.sh/ this is your preview link @aksy2512 add it to the pr template comment

**Comment by aksy2512** [comment]
@YoshithaRathnayake  Thanks! Done

**Pull request closed without merging**
