### PR TITLE
Align the paragraph center

### PR DESCRIPTION
**Pull request by Shruti1998-mona**

### CODE REVIEW

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
Can you add a small description for this pr in the comment box of this pr @Shruti1998-mona

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
can you pls resolve the conflicts @Shruti1998-mona

**Comment by Shruti1998-mona** [comment]
Decreased the size fof the image.

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
Align the paragraph center, add this as the topic of this pr @Shruti1998-mona

**Comment by YoshithaRathnayake** [comment]
> Decreased the size fof the image.

Nice! @Shruti1998-mona

**Comment by YoshithaRathnayake** [comment]
> Align the paragraph center, add this as the topic of this pr @Shruti1998-mona

@Shruti1998-mona can you do this?

**Review by YoshithaRathnayake — APPROVED** [review]
Good Job !
Thank You @Shruti1998-mona

**Pull request merged**
